// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package ins

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Implied-1]
	_ = x[Accumulator-2]
	_ = x[Immediate-3]
	_ = x[ZeroPage-4]
	_ = x[ZeroPageX-5]
	_ = x[ZeroPageY-6]
	_ = x[Relative-7]
	_ = x[Absolute-8]
	_ = x[AbsoluteX-9]
	_ = x[AbsoluteY-10]
	_ = x[Indirect-11]
	_ = x[IndirectX-12]
	_ = x[IndirectY-13]
}

const _Mode_name = "ImpliedAccumulatorImmediateZeroPageZeroPageXZeroPageYRelativeAbsoluteAbsoluteXAbsoluteYIndirectIndirectXIndirectY"

var _Mode_index = [...]uint8{0, 7, 18, 27, 35, 44, 53, 61, 69, 78, 87, 95, 104, 113}

func (i Mode) String() string {
	i -= 1
	if i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
