// Code generated by "stringer -type=Name"; DO NOT EDIT.

package ins

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ADC-1]
	_ = x[AND-2]
	_ = x[ASL-3]
	_ = x[BCC-4]
	_ = x[BCS-5]
	_ = x[BEQ-6]
	_ = x[BIT-7]
	_ = x[BMI-8]
	_ = x[BNE-9]
	_ = x[BPL-10]
	_ = x[BRK-11]
	_ = x[BVC-12]
	_ = x[BVS-13]
	_ = x[CLC-14]
	_ = x[CLD-15]
	_ = x[CLI-16]
	_ = x[CLV-17]
	_ = x[CMP-18]
	_ = x[CPX-19]
	_ = x[CPY-20]
	_ = x[DEC-21]
	_ = x[DEX-22]
	_ = x[DEY-23]
	_ = x[EOR-24]
	_ = x[INC-25]
	_ = x[INX-26]
	_ = x[INY-27]
	_ = x[JMP-28]
	_ = x[JSP-29]
	_ = x[JSR-30]
	_ = x[LDA-31]
	_ = x[LDX-32]
	_ = x[LDY-33]
	_ = x[LSR-34]
	_ = x[NOP-35]
	_ = x[ORA-36]
	_ = x[PHA-37]
	_ = x[PHP-38]
	_ = x[PLA-39]
	_ = x[PLP-40]
	_ = x[ROL-41]
	_ = x[ROR-42]
	_ = x[RTI-43]
	_ = x[RTS-44]
	_ = x[SBC-45]
	_ = x[SEC-46]
	_ = x[SED-47]
	_ = x[SEI-48]
	_ = x[STA-49]
	_ = x[STX-50]
	_ = x[STY-51]
	_ = x[TAX-52]
	_ = x[TAY-53]
	_ = x[TSX-54]
	_ = x[TXA-55]
	_ = x[TXS-56]
	_ = x[TYA-57]
}

const _Name_name = "ADCANDASLBCCBCSBEQBITBMIBNEBPLBRKBVCBVSCLCCLDCLICLVCMPCPXCPYDECDEXDEYEORINCINXINYJMPJSPJSRLDALDXLDYLSRNOPORAPHAPHPPLAPLPROLRORRTIRTSSBCSECSEDSEISTASTXSTYTAXTAYTSXTXATXSTYA"

var _Name_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168, 171}

func (i Name) String() string {
	i -= 1
	if i >= Name(len(_Name_index)-1) {
		return "Name(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Name_name[_Name_index[i]:_Name_index[i+1]]
}
