// Code generated by "python gen.py && go fmt"; DO NOT EDIT.

package ins

const (
	ADCImmediate   = 0x69
	ADCZeroPage    = 0x65
	ADCZeroPageX   = 0x75
	ADCAbsolute    = 0x6D
	ADCAbsoluteX   = 0x7D
	ADCAbsoluteY   = 0x79
	ADCIndirectX   = 0x61
	ADCIndirectY   = 0x71
	ANDImmediate   = 0x29
	ANDZeroPage    = 0x25
	ANDZeroPageX   = 0x35
	ANDAbsolute    = 0x2D
	ANDAbsoluteX   = 0x3D
	ANDAbsoluteY   = 0x39
	ANDIndirectX   = 0x21
	ANDIndirectY   = 0x31
	ASLAccumulator = 0x0A
	ASLZeroPage    = 0x06
	ASLZeroPageX   = 0x16
	ASLAbsolute    = 0x0E
	ASLAbsoluteX   = 0x1E
	BCCRelative    = 0x90
	BCSRelative    = 0xB0
	BEQRelative    = 0xF0
	BITZeroPage    = 0x24
	BITAbsolute    = 0x2C
	BMIRelative    = 0x30
	BNERelative    = 0xD0
	BPLRelative    = 0x10
	BRKImplied     = 0x0
	BVCRelative    = 0x50
	BVSRelative    = 0x70
	CLCImplied     = 0x18
	CLDImplied     = 0xD8
	CLIImplied     = 0x58
	CLVImplied     = 0xB8
	CMPImmediate   = 0xC9
	CMPZeroPage    = 0xC5
	CMPZeroPageX   = 0xD5
	CMPAbsolute    = 0xCD
	CMPAbsoluteX   = 0xDD
	CMPAbsoluteY   = 0xD9
	CMPIndirectX   = 0xC1
	CMPIndirectY   = 0xD1
	CPXImmediate   = 0xE0
	CPXZeroPage    = 0xE4
	CPXAbsolute    = 0xEC
	CPYImmediate   = 0xC0
	CPYZeroPage    = 0xC4
	CPYAbsolute    = 0xCC
	DECZeroPage    = 0xC6
	DECZeroPageX   = 0xD6
	DECAbsolute    = 0xCE
	DECAbsoluteX   = 0xDE
	DEXImplied     = 0xCA
	DEYImplied     = 0x88
	EORImmediate   = 0x49
	EORZeroPage    = 0x45
	EORZeroPageX   = 0x55
	EORAbsolute    = 0x4D
	EORAbsoluteX   = 0x5D
	EORAbsoluteY   = 0x59
	EORIndirectX   = 0x41
	EORIndirectY   = 0x51
	INCZeroPage    = 0xE6
	INCZeroPageX   = 0xF6
	INCAbsolute    = 0xEE
	INCAbsoluteX   = 0xFE
	INXImplied     = 0xE8
	INYImplied     = 0xC8
	JMPAbsolute    = 0x4C
	JMPIndirect    = 0x6C
	JSRAbsolute    = 0x20
	LDAImmediate   = 0xA9
	LDAZeroPage    = 0xA5
	LDAZeroPageX   = 0xB5
	LDAAbsolute    = 0xAD
	LDAAbsoluteX   = 0xBD
	LDAAbsoluteY   = 0xB9
	LDAIndirectX   = 0xA1
	LDAIndirectY   = 0xB1
	LDXImmediate   = 0xA2
	LDXZeroPage    = 0xA6
	LDXZeroPageY   = 0xB6
	LDXAbsolute    = 0xAE
	LDXAbsoluteY   = 0xBE
	LDYImmediate   = 0xA0
	LDYZeroPage    = 0xA4
	LDYZeroPageX   = 0xB4
	LDYAbsolute    = 0xAC
	LDYAbsoluteX   = 0xBC
	LSRAccumulator = 0x4A
	LSRZeroPage    = 0x46
	LSRZeroPageX   = 0x56
	LSRAbsolute    = 0x4E
	LSRAbsoluteX   = 0x5E
	NOPImplied     = 0xEA
	ORAImmediate   = 0x09
	ORAZeroPage    = 0x05
	ORAZeroPageX   = 0x15
	ORAAbsolute    = 0x0D
	ORAAbsoluteX   = 0x1D
	ORAAbsoluteY   = 0x19
	ORAIndirectX   = 0x01
	ORAIndirectY   = 0x11
	PHAImplied     = 0x48
	PHPImplied     = 0x08
	PLAImplied     = 0x68
	PLPImplied     = 0x28
	ROLAccumulator = 0x2A
	ROLZeroPage    = 0x26
	ROLZeroPageX   = 0x36
	ROLAbsolute    = 0x2E
	ROLAbsoluteX   = 0x3E
	RORAccumulator = 0x6A
	RORZeroPage    = 0x66
	RORZeroPageX   = 0x76
	RORAbsolute    = 0x6E
	RORAbsoluteX   = 0x7E
	RTIImplied     = 0x40
	RTSImplied     = 0x60
	SBCImmediate   = 0xE9
	SBCZeroPage    = 0xE5
	SBCZeroPageX   = 0xF5
	SBCAbsolute    = 0xED
	SBCAbsoluteX   = 0xFD
	SBCAbsoluteY   = 0xF9
	SBCIndirectX   = 0xE1
	SBCIndirectY   = 0xF1
	SECImplied     = 0x38
	SEDImplied     = 0xF8
	SEIImplied     = 0x78
	STAZeroPage    = 0x85
	STAZeroPageX   = 0x95
	STAAbsolute    = 0x8D
	STAAbsoluteX   = 0x9D
	STAAbsoluteY   = 0x99
	STAIndirectX   = 0x81
	STAIndirectY   = 0x91
	STXZeroPage    = 0x86
	STXZeroPageY   = 0x96
	STXAbsolute    = 0x8E
	STYZeroPage    = 0x84
	STYZeroPageX   = 0x94
	STYAbsolute    = 0x8C
	TAXImplied     = 0xAA
	TAYImplied     = 0xA8
	TSXImplied     = 0xBA
	TXAImplied     = 0x8A
	TXSImplied     = 0x9A
	TYAImplied     = 0x98
)

func init() {

	Table[ADCImmediate] = Ins{
		Name:   ADC,
		Op:     0x69,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[ADCZeroPage] = Ins{
		Name:   ADC,
		Op:     0x65,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[ADCZeroPageX] = Ins{
		Name:   ADC,
		Op:     0x75,
		Mode:   ZeroPageX,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[ADCAbsolute] = Ins{
		Name:   ADC,
		Op:     0x6D,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[ADCAbsoluteX] = Ins{
		Name:   ADC,
		Op:     0x7D,
		Mode:   AbsoluteX,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[ADCAbsoluteY] = Ins{
		Name:   ADC,
		Op:     0x79,
		Mode:   AbsoluteY,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[ADCIndirectX] = Ins{
		Name:   ADC,
		Op:     0x61,
		Mode:   IndirectX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[ADCIndirectY] = Ins{
		Name:   ADC,
		Op:     0x71,
		Mode:   IndirectY,
		Cycles: 5,
		Page:   Cross,
		Bytes:  2,
	}

	Table[ANDImmediate] = Ins{
		Name:   AND,
		Op:     0x29,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[ANDZeroPage] = Ins{
		Name:   AND,
		Op:     0x25,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[ANDZeroPageX] = Ins{
		Name:   AND,
		Op:     0x35,
		Mode:   ZeroPageX,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[ANDAbsolute] = Ins{
		Name:   AND,
		Op:     0x2D,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[ANDAbsoluteX] = Ins{
		Name:   AND,
		Op:     0x3D,
		Mode:   AbsoluteX,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[ANDAbsoluteY] = Ins{
		Name:   AND,
		Op:     0x39,
		Mode:   AbsoluteY,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[ANDIndirectX] = Ins{
		Name:   AND,
		Op:     0x21,
		Mode:   IndirectX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[ANDIndirectY] = Ins{
		Name:   AND,
		Op:     0x31,
		Mode:   IndirectY,
		Cycles: 5,
		Page:   Cross,
		Bytes:  2,
	}

	Table[ASLAccumulator] = Ins{
		Name:   ASL,
		Op:     0x0A,
		Mode:   Accumulator,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[ASLZeroPage] = Ins{
		Name:   ASL,
		Op:     0x06,
		Mode:   ZeroPage,
		Cycles: 5,
		Page:   None,
		Bytes:  2,
	}

	Table[ASLZeroPageX] = Ins{
		Name:   ASL,
		Op:     0x16,
		Mode:   ZeroPageX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[ASLAbsolute] = Ins{
		Name:   ASL,
		Op:     0x0E,
		Mode:   Absolute,
		Cycles: 6,
		Page:   None,
		Bytes:  3,
	}

	Table[ASLAbsoluteX] = Ins{
		Name:   ASL,
		Op:     0x1E,
		Mode:   AbsoluteX,
		Cycles: 7,
		Page:   None,
		Bytes:  3,
	}

	Table[BCCRelative] = Ins{
		Name:   BCC,
		Op:     0x90,
		Mode:   Relative,
		Cycles: 2,
		Page:   Branch,
		Bytes:  2,
	}

	Table[BCSRelative] = Ins{
		Name:   BCS,
		Op:     0xB0,
		Mode:   Relative,
		Cycles: 2,
		Page:   Branch,
		Bytes:  2,
	}

	Table[BEQRelative] = Ins{
		Name:   BEQ,
		Op:     0xF0,
		Mode:   Relative,
		Cycles: 2,
		Page:   Branch,
		Bytes:  2,
	}

	Table[BITZeroPage] = Ins{
		Name:   BIT,
		Op:     0x24,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[BITAbsolute] = Ins{
		Name:   BIT,
		Op:     0x2C,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[BMIRelative] = Ins{
		Name:   BMI,
		Op:     0x30,
		Mode:   Relative,
		Cycles: 2,
		Page:   Branch,
		Bytes:  2,
	}

	Table[BNERelative] = Ins{
		Name:   BNE,
		Op:     0xD0,
		Mode:   Relative,
		Cycles: 2,
		Page:   Branch,
		Bytes:  2,
	}

	Table[BPLRelative] = Ins{
		Name:   BPL,
		Op:     0x10,
		Mode:   Relative,
		Cycles: 2,
		Page:   Branch,
		Bytes:  2,
	}

	Table[BRKImplied] = Ins{
		Name:   BRK,
		Op:     0x0,
		Mode:   Implied,
		Cycles: 7,
		Page:   None,
		Bytes:  1,
	}

	Table[BVCRelative] = Ins{
		Name:   BVC,
		Op:     0x50,
		Mode:   Relative,
		Cycles: 2,
		Page:   Branch,
		Bytes:  2,
	}

	Table[BVSRelative] = Ins{
		Name:   BVS,
		Op:     0x70,
		Mode:   Relative,
		Cycles: 2,
		Page:   Branch,
		Bytes:  2,
	}

	Table[CLCImplied] = Ins{
		Name:   CLC,
		Op:     0x18,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[CLDImplied] = Ins{
		Name:   CLD,
		Op:     0xD8,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[CLIImplied] = Ins{
		Name:   CLI,
		Op:     0x58,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[CLVImplied] = Ins{
		Name:   CLV,
		Op:     0xB8,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[CMPImmediate] = Ins{
		Name:   CMP,
		Op:     0xC9,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[CMPZeroPage] = Ins{
		Name:   CMP,
		Op:     0xC5,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[CMPZeroPageX] = Ins{
		Name:   CMP,
		Op:     0xD5,
		Mode:   ZeroPageX,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[CMPAbsolute] = Ins{
		Name:   CMP,
		Op:     0xCD,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[CMPAbsoluteX] = Ins{
		Name:   CMP,
		Op:     0xDD,
		Mode:   AbsoluteX,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[CMPAbsoluteY] = Ins{
		Name:   CMP,
		Op:     0xD9,
		Mode:   AbsoluteY,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[CMPIndirectX] = Ins{
		Name:   CMP,
		Op:     0xC1,
		Mode:   IndirectX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[CMPIndirectY] = Ins{
		Name:   CMP,
		Op:     0xD1,
		Mode:   IndirectY,
		Cycles: 5,
		Page:   Cross,
		Bytes:  2,
	}

	Table[CPXImmediate] = Ins{
		Name:   CPX,
		Op:     0xE0,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[CPXZeroPage] = Ins{
		Name:   CPX,
		Op:     0xE4,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[CPXAbsolute] = Ins{
		Name:   CPX,
		Op:     0xEC,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[CPYImmediate] = Ins{
		Name:   CPY,
		Op:     0xC0,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[CPYZeroPage] = Ins{
		Name:   CPY,
		Op:     0xC4,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[CPYAbsolute] = Ins{
		Name:   CPY,
		Op:     0xCC,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[DECZeroPage] = Ins{
		Name:   DEC,
		Op:     0xC6,
		Mode:   ZeroPage,
		Cycles: 5,
		Page:   None,
		Bytes:  2,
	}

	Table[DECZeroPageX] = Ins{
		Name:   DEC,
		Op:     0xD6,
		Mode:   ZeroPageX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[DECAbsolute] = Ins{
		Name:   DEC,
		Op:     0xCE,
		Mode:   Absolute,
		Cycles: 6,
		Page:   None,
		Bytes:  3,
	}

	Table[DECAbsoluteX] = Ins{
		Name:   DEC,
		Op:     0xDE,
		Mode:   AbsoluteX,
		Cycles: 7,
		Page:   None,
		Bytes:  3,
	}

	Table[DEXImplied] = Ins{
		Name:   DEX,
		Op:     0xCA,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[DEYImplied] = Ins{
		Name:   DEY,
		Op:     0x88,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[EORImmediate] = Ins{
		Name:   EOR,
		Op:     0x49,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[EORZeroPage] = Ins{
		Name:   EOR,
		Op:     0x45,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[EORZeroPageX] = Ins{
		Name:   EOR,
		Op:     0x55,
		Mode:   ZeroPageX,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[EORAbsolute] = Ins{
		Name:   EOR,
		Op:     0x4D,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[EORAbsoluteX] = Ins{
		Name:   EOR,
		Op:     0x5D,
		Mode:   AbsoluteX,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[EORAbsoluteY] = Ins{
		Name:   EOR,
		Op:     0x59,
		Mode:   AbsoluteY,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[EORIndirectX] = Ins{
		Name:   EOR,
		Op:     0x41,
		Mode:   IndirectX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[EORIndirectY] = Ins{
		Name:   EOR,
		Op:     0x51,
		Mode:   IndirectY,
		Cycles: 5,
		Page:   Cross,
		Bytes:  2,
	}

	Table[INCZeroPage] = Ins{
		Name:   INC,
		Op:     0xE6,
		Mode:   ZeroPage,
		Cycles: 5,
		Page:   None,
		Bytes:  2,
	}

	Table[INCZeroPageX] = Ins{
		Name:   INC,
		Op:     0xF6,
		Mode:   ZeroPageX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[INCAbsolute] = Ins{
		Name:   INC,
		Op:     0xEE,
		Mode:   Absolute,
		Cycles: 6,
		Page:   None,
		Bytes:  3,
	}

	Table[INCAbsoluteX] = Ins{
		Name:   INC,
		Op:     0xFE,
		Mode:   AbsoluteX,
		Cycles: 7,
		Page:   None,
		Bytes:  3,
	}

	Table[INXImplied] = Ins{
		Name:   INX,
		Op:     0xE8,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[INYImplied] = Ins{
		Name:   INY,
		Op:     0xC8,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[JMPAbsolute] = Ins{
		Name:   JMP,
		Op:     0x4C,
		Mode:   Absolute,
		Cycles: 3,
		Page:   None,
		Bytes:  3,
	}

	Table[JMPIndirect] = Ins{
		Name:   JMP,
		Op:     0x6C,
		Mode:   Indirect,
		Cycles: 5,
		Page:   None,
		Bytes:  3,
	}

	Table[JSRAbsolute] = Ins{
		Name:   JSR,
		Op:     0x20,
		Mode:   Absolute,
		Cycles: 6,
		Page:   None,
		Bytes:  3,
	}

	Table[LDAImmediate] = Ins{
		Name:   LDA,
		Op:     0xA9,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[LDAZeroPage] = Ins{
		Name:   LDA,
		Op:     0xA5,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[LDAZeroPageX] = Ins{
		Name:   LDA,
		Op:     0xB5,
		Mode:   ZeroPageX,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[LDAAbsolute] = Ins{
		Name:   LDA,
		Op:     0xAD,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[LDAAbsoluteX] = Ins{
		Name:   LDA,
		Op:     0xBD,
		Mode:   AbsoluteX,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[LDAAbsoluteY] = Ins{
		Name:   LDA,
		Op:     0xB9,
		Mode:   AbsoluteY,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[LDAIndirectX] = Ins{
		Name:   LDA,
		Op:     0xA1,
		Mode:   IndirectX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[LDAIndirectY] = Ins{
		Name:   LDA,
		Op:     0xB1,
		Mode:   IndirectY,
		Cycles: 5,
		Page:   Cross,
		Bytes:  2,
	}

	Table[LDXImmediate] = Ins{
		Name:   LDX,
		Op:     0xA2,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[LDXZeroPage] = Ins{
		Name:   LDX,
		Op:     0xA6,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[LDXZeroPageY] = Ins{
		Name:   LDX,
		Op:     0xB6,
		Mode:   ZeroPageY,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[LDXAbsolute] = Ins{
		Name:   LDX,
		Op:     0xAE,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[LDXAbsoluteY] = Ins{
		Name:   LDX,
		Op:     0xBE,
		Mode:   AbsoluteY,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[LDYImmediate] = Ins{
		Name:   LDY,
		Op:     0xA0,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[LDYZeroPage] = Ins{
		Name:   LDY,
		Op:     0xA4,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[LDYZeroPageX] = Ins{
		Name:   LDY,
		Op:     0xB4,
		Mode:   ZeroPageX,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[LDYAbsolute] = Ins{
		Name:   LDY,
		Op:     0xAC,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[LDYAbsoluteX] = Ins{
		Name:   LDY,
		Op:     0xBC,
		Mode:   AbsoluteX,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[LSRAccumulator] = Ins{
		Name:   LSR,
		Op:     0x4A,
		Mode:   Accumulator,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[LSRZeroPage] = Ins{
		Name:   LSR,
		Op:     0x46,
		Mode:   ZeroPage,
		Cycles: 5,
		Page:   None,
		Bytes:  2,
	}

	Table[LSRZeroPageX] = Ins{
		Name:   LSR,
		Op:     0x56,
		Mode:   ZeroPageX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[LSRAbsolute] = Ins{
		Name:   LSR,
		Op:     0x4E,
		Mode:   Absolute,
		Cycles: 6,
		Page:   None,
		Bytes:  3,
	}

	Table[LSRAbsoluteX] = Ins{
		Name:   LSR,
		Op:     0x5E,
		Mode:   AbsoluteX,
		Cycles: 7,
		Page:   None,
		Bytes:  3,
	}

	Table[NOPImplied] = Ins{
		Name:   NOP,
		Op:     0xEA,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[ORAImmediate] = Ins{
		Name:   ORA,
		Op:     0x09,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[ORAZeroPage] = Ins{
		Name:   ORA,
		Op:     0x05,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[ORAZeroPageX] = Ins{
		Name:   ORA,
		Op:     0x15,
		Mode:   ZeroPageX,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[ORAAbsolute] = Ins{
		Name:   ORA,
		Op:     0x0D,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[ORAAbsoluteX] = Ins{
		Name:   ORA,
		Op:     0x1D,
		Mode:   AbsoluteX,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[ORAAbsoluteY] = Ins{
		Name:   ORA,
		Op:     0x19,
		Mode:   AbsoluteY,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[ORAIndirectX] = Ins{
		Name:   ORA,
		Op:     0x01,
		Mode:   IndirectX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[ORAIndirectY] = Ins{
		Name:   ORA,
		Op:     0x11,
		Mode:   IndirectY,
		Cycles: 5,
		Page:   Cross,
		Bytes:  2,
	}

	Table[PHAImplied] = Ins{
		Name:   PHA,
		Op:     0x48,
		Mode:   Implied,
		Cycles: 3,
		Page:   None,
		Bytes:  1,
	}

	Table[PHPImplied] = Ins{
		Name:   PHP,
		Op:     0x08,
		Mode:   Implied,
		Cycles: 3,
		Page:   None,
		Bytes:  1,
	}

	Table[PLAImplied] = Ins{
		Name:   PLA,
		Op:     0x68,
		Mode:   Implied,
		Cycles: 4,
		Page:   None,
		Bytes:  1,
	}

	Table[PLPImplied] = Ins{
		Name:   PLP,
		Op:     0x28,
		Mode:   Implied,
		Cycles: 4,
		Page:   None,
		Bytes:  1,
	}

	Table[ROLAccumulator] = Ins{
		Name:   ROL,
		Op:     0x2A,
		Mode:   Accumulator,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[ROLZeroPage] = Ins{
		Name:   ROL,
		Op:     0x26,
		Mode:   ZeroPage,
		Cycles: 5,
		Page:   None,
		Bytes:  2,
	}

	Table[ROLZeroPageX] = Ins{
		Name:   ROL,
		Op:     0x36,
		Mode:   ZeroPageX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[ROLAbsolute] = Ins{
		Name:   ROL,
		Op:     0x2E,
		Mode:   Absolute,
		Cycles: 6,
		Page:   None,
		Bytes:  3,
	}

	Table[ROLAbsoluteX] = Ins{
		Name:   ROL,
		Op:     0x3E,
		Mode:   AbsoluteX,
		Cycles: 7,
		Page:   None,
		Bytes:  3,
	}

	Table[RORAccumulator] = Ins{
		Name:   ROR,
		Op:     0x6A,
		Mode:   Accumulator,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[RORZeroPage] = Ins{
		Name:   ROR,
		Op:     0x66,
		Mode:   ZeroPage,
		Cycles: 5,
		Page:   None,
		Bytes:  2,
	}

	Table[RORZeroPageX] = Ins{
		Name:   ROR,
		Op:     0x76,
		Mode:   ZeroPageX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[RORAbsolute] = Ins{
		Name:   ROR,
		Op:     0x6E,
		Mode:   Absolute,
		Cycles: 6,
		Page:   None,
		Bytes:  3,
	}

	Table[RORAbsoluteX] = Ins{
		Name:   ROR,
		Op:     0x7E,
		Mode:   AbsoluteX,
		Cycles: 7,
		Page:   None,
		Bytes:  3,
	}

	Table[RTIImplied] = Ins{
		Name:   RTI,
		Op:     0x40,
		Mode:   Implied,
		Cycles: 6,
		Page:   None,
		Bytes:  1,
	}

	Table[RTSImplied] = Ins{
		Name:   RTS,
		Op:     0x60,
		Mode:   Implied,
		Cycles: 6,
		Page:   None,
		Bytes:  1,
	}

	Table[SBCImmediate] = Ins{
		Name:   SBC,
		Op:     0xE9,
		Mode:   Immediate,
		Cycles: 2,
		Page:   None,
		Bytes:  2,
	}

	Table[SBCZeroPage] = Ins{
		Name:   SBC,
		Op:     0xE5,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[SBCZeroPageX] = Ins{
		Name:   SBC,
		Op:     0xF5,
		Mode:   ZeroPageX,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[SBCAbsolute] = Ins{
		Name:   SBC,
		Op:     0xED,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[SBCAbsoluteX] = Ins{
		Name:   SBC,
		Op:     0xFD,
		Mode:   AbsoluteX,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[SBCAbsoluteY] = Ins{
		Name:   SBC,
		Op:     0xF9,
		Mode:   AbsoluteY,
		Cycles: 4,
		Page:   Cross,
		Bytes:  3,
	}

	Table[SBCIndirectX] = Ins{
		Name:   SBC,
		Op:     0xE1,
		Mode:   IndirectX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[SBCIndirectY] = Ins{
		Name:   SBC,
		Op:     0xF1,
		Mode:   IndirectY,
		Cycles: 5,
		Page:   Cross,
		Bytes:  2,
	}

	Table[SECImplied] = Ins{
		Name:   SEC,
		Op:     0x38,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[SEDImplied] = Ins{
		Name:   SED,
		Op:     0xF8,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[SEIImplied] = Ins{
		Name:   SEI,
		Op:     0x78,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[STAZeroPage] = Ins{
		Name:   STA,
		Op:     0x85,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[STAZeroPageX] = Ins{
		Name:   STA,
		Op:     0x95,
		Mode:   ZeroPageX,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[STAAbsolute] = Ins{
		Name:   STA,
		Op:     0x8D,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[STAAbsoluteX] = Ins{
		Name:   STA,
		Op:     0x9D,
		Mode:   AbsoluteX,
		Cycles: 5,
		Page:   None,
		Bytes:  3,
	}

	Table[STAAbsoluteY] = Ins{
		Name:   STA,
		Op:     0x99,
		Mode:   AbsoluteY,
		Cycles: 5,
		Page:   None,
		Bytes:  3,
	}

	Table[STAIndirectX] = Ins{
		Name:   STA,
		Op:     0x81,
		Mode:   IndirectX,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[STAIndirectY] = Ins{
		Name:   STA,
		Op:     0x91,
		Mode:   IndirectY,
		Cycles: 6,
		Page:   None,
		Bytes:  2,
	}

	Table[STXZeroPage] = Ins{
		Name:   STX,
		Op:     0x86,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[STXZeroPageY] = Ins{
		Name:   STX,
		Op:     0x96,
		Mode:   ZeroPageY,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[STXAbsolute] = Ins{
		Name:   STX,
		Op:     0x8E,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[STYZeroPage] = Ins{
		Name:   STY,
		Op:     0x84,
		Mode:   ZeroPage,
		Cycles: 3,
		Page:   None,
		Bytes:  2,
	}

	Table[STYZeroPageX] = Ins{
		Name:   STY,
		Op:     0x94,
		Mode:   ZeroPageX,
		Cycles: 4,
		Page:   None,
		Bytes:  2,
	}

	Table[STYAbsolute] = Ins{
		Name:   STY,
		Op:     0x8C,
		Mode:   Absolute,
		Cycles: 4,
		Page:   None,
		Bytes:  3,
	}

	Table[TAXImplied] = Ins{
		Name:   TAX,
		Op:     0xAA,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[TAYImplied] = Ins{
		Name:   TAY,
		Op:     0xA8,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[TSXImplied] = Ins{
		Name:   TSX,
		Op:     0xBA,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[TXAImplied] = Ins{
		Name:   TXA,
		Op:     0x8A,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[TXSImplied] = Ins{
		Name:   TXS,
		Op:     0x9A,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}

	Table[TYAImplied] = Ins{
		Name:   TYA,
		Op:     0x98,
		Mode:   Implied,
		Cycles: 2,
		Page:   None,
		Bytes:  1,
	}
}
