// Code generated by "stringer --type=PagePolicy"; DO NOT EDIT.

package ins

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
}

const _PagePolicy_name = "None"

var _PagePolicy_index = [...]uint8{0, 4}

func (i PagePolicy) String() string {
	if i >= PagePolicy(len(_PagePolicy_index)-1) {
		return "PagePolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PagePolicy_name[_PagePolicy_index[i]:_PagePolicy_index[i+1]]
}
