// Code generated by "stringer --type=SType"; DO NOT EDIT.

package lisa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Default-1]
	_ = x[Constants-2]
	_ = x[RawData-4]
	_ = x[Jump-8]
	_ = x[Branch-16]
}

const (
	_SType_name_0 = "DefaultConstants"
	_SType_name_1 = "RawData"
	_SType_name_2 = "Jump"
	_SType_name_3 = "Branch"
)

var (
	_SType_index_0 = [...]uint8{0, 7, 16}
)

func (i SType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _SType_name_0[_SType_index_0[i]:_SType_index_0[i+1]]
	case i == 4:
		return _SType_name_1
	case i == 8:
		return _SType_name_2
	case i == 16:
		return _SType_name_3
	default:
		return "SType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
